// header file generated by lasagnaphil
#ifndef  TXT_HEADER_depth_frag_shader
#define  TXT_HEADER_depth_frag_shader


const char depth_frag_shader [] =
"#version 330 core\n"
"\n"
"void main()\n"
"{\n"
"}\n"
;


#endif  // #ifdef TXT_HEADER_depth_frag_shader
