// header file generated by lasagnaphil
#ifndef  TXT_HEADER_depth_debug_vert_shader
#define  TXT_HEADER_depth_debug_vert_shader


const char depth_debug_vert_shader [] =
"#version 330 core\n"
"layout (location = 0) in vec3 aPos;\n"
"layout (location = 1) in vec2 aTexCoords;\n"
"\n"
"out vec2 TexCoords;\n"
"\n"
"void main()\n"
"{\n"
"    TexCoords = aTexCoords;\n"
"    gl_Position = vec4(aPos, 1.0);\n"
"}\n"
;


#endif  // #ifdef TXT_HEADER_depth_debug_vert_shader
