// header file generated by lasagnaphil
#ifndef  TXT_HEADER_line2d_vert_shader
#define  TXT_HEADER_line2d_vert_shader


const char line2d_vert_shader [] =
"#version 330 core\n"
"\n"
"layout (location = 0) in vec2 inPos;\n"
"\n"
"uniform float height;\n"
"uniform float pointSize;\n"
"\n"
"uniform mat4 model;\n"
"uniform mat4 view;\n"
"uniform mat4 proj;\n"
"\n"
"void main() {\n"
"    gl_Position = proj * view * model * vec4(inPos.x, height, inPos.y, 1.0f);\n"
"    gl_PointSize = pointSize;\n"
"}\n"
;


#endif  // #ifdef TXT_HEADER_line2d_vert_shader
