// header file generated by lasagnaphil
#ifndef  TXT_HEADER_line2d_frag_shader
#define  TXT_HEADER_line2d_frag_shader


const char line2d_frag_shader [] =
"#version 330 core\n"
"\n"
"uniform vec4 color;\n"
"\n"
"out vec4 fragColor;\n"
"\n"
"void main() {\n"
"    fragColor = color;\n"
"}\n"
;


#endif  // #ifdef TXT_HEADER_line2d_frag_shader
