// header file generated by lasagnaphil
#ifndef  TXT_HEADER_phong_shadows_vert_shader
#define  TXT_HEADER_phong_shadows_vert_shader


const char phong_shadows_vert_shader [] =
"#version 330 core\n"
"\n"
"layout (location = 0) in vec3 inPos;\n"
"layout (location = 1) in vec3 inNormal;\n"
"layout (location = 2) in vec2 inTexCoord;\n"
"\n"
"out VS_OUT {\n"
"    vec3 FragPos;\n"
"    vec3 Normal;\n"
"    vec2 TexCoords;\n"
"    vec4 FragPos_DirLightSpace;\n"
"} vs_out;\n"
"\n"
"uniform mat4 model;\n"
"uniform mat4 view;\n"
"uniform mat4 proj;\n"
"uniform mat4 dirLightSpaceMatrix;\n"
"\n"
"void main()\n"
"{\n"
"    vs_out.FragPos = vec3(model * vec4(inPos, 1.0));\n"
"    vs_out.Normal = mat3(transpose(inverse(model))) * inNormal;\n"
"    vs_out.TexCoords = inTexCoord;\n"
"    vs_out.FragPos_DirLightSpace = dirLightSpaceMatrix * vec4(vs_out.FragPos, 1.0);\n"
"    gl_Position = proj * view * model * vec4(inPos, 1.0);\n"
"}\n"
;


#endif  // #ifdef TXT_HEADER_phong_shadows_vert_shader
