// header file generated by lasagnaphil
#ifndef  TXT_HEADER_phong_vert_shader
#define  TXT_HEADER_phong_vert_shader


const char phong_vert_shader [] =
"#version 330 core\n"
"\n"
"layout (location = 0) in vec3 inPos;\n"
"layout (location = 1) in vec3 inNormal;\n"
"layout (location = 2) in vec2 inTexCoord;\n"
"\n"
"uniform mat4 model;\n"
"uniform mat4 view;\n"
"uniform mat4 proj;\n"
"\n"
"out vec3 fragPos;\n"
"out vec3 normal;\n"
"out vec2 texCoord;\n"
"\n"
"void main()\n"
"{\n"
"    gl_Position = proj * view * model * vec4(inPos, 1.0);\n"
"    fragPos = vec3(model * vec4(inPos, 1.0));\n"
"    normal = mat3(transpose(inverse(model))) * inNormal;\n"
"    texCoord = inTexCoord;\n"
"}\n"
;


#endif  // #ifdef TXT_HEADER_phong_vert_shader
