// header file generated by lasagnaphil
#ifndef  TXT_HEADER_point_vert_shader
#define  TXT_HEADER_point_vert_shader


const char point_vert_shader [] =
"#version 330 core\n"
"\n"
"layout (location = 0) in vec3 inPos;\n"
"\n"
"uniform mat4 model;\n"
"uniform mat4 view;\n"
"uniform mat4 proj;\n"
"\n"
"void main() {\n"
"    gl_Position = proj * view * model * vec4(inPos, 1.0);\n"
"}\n"
;


#endif  // #ifdef TXT_HEADER_point_vert_shader
